---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker
#
# tasks file for glpi_agent

# Specific tasks per OS [[[1
- name: Include tasks per OS
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
