---
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:

  - name: systemd-debian11
    image: jrei/systemd-debian:11
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: systemd-debian10
    image: jrei/systemd-debian:10
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: systemd-ubuntu2204
    image: jrei/systemd-ubuntu:22.04
    privileged: True
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
verifier:
  name: ansible
