---
name: Molecule.setup-python

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip3 install yamllint ansible-lint ansible "molecule[lint,docker]"

      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install community.docker

      - name: Run Molecule tests.
        run: "molecule test"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
